// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankingSystem.Models
{
    public partial class Customers
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public decimal? Balance { get; set; }
        public string AccountNumber { get; set; }
        public string Image { get; set; }
        public string BalanceAfterEdit { get { return "$" + Balance; } }
    }
}