// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BankingSystem.Models
{
    public partial class Customers
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Name field is requird")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Email field is requird")]
        [DataType(DataType.EmailAddress,ErrorMessage ="Email address not valid")]
        public string Email { get; set; }
        public int? Balance { get; set; }
    }
}